version: '3.2'
    
services:
  python:
    image: test_project/python:1.0
    build: ./python
    container_name: 'test_project_python'
    stdin_open: true
    tty: true
    working_dir: '/tmp/work'
    volumes:
      - ../:/tmp/work